### ISSUE TITLE
.bat File not working

### ISSUE THREAD

**Issue by AlejandroDZ18** [DamnMerc/Vanilla-Updater#2]
If i execute the .bat File it just gives me a random error message

Error: Cannot find module 'replace-in-file'

**Comment by LordMerc** [comment]
That's my fault as I forgot to include in the dependencies you will need to install that package also.
npm i replace-in-file

**Comment by AlejandroDZ18** [comment]
Thank you for the Help!

ps : you will also require inquirer

**Comment by LordMerc** [comment]
Oh yea, that was form sas's pull. I'll add that too, thanks!
