### ISSUE TITLE
I get a error :c

### ISSUE THREAD

**Issue by heapframe** [DamnMerc/Vanilla-Updater#3]
(node:3432) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '../Roblox/Versions'
    at Object.readdirSync (fs.js:948:3)
    at getDirectories (C:\Users\calic\Downloads\Vanilla-Updater-master\Vanilla-Updater-master\index.js:4:6)
    at uploadImage (C:\Users\calic\Downloads\Vanilla-Updater-master\Vanilla-Updater-master\index.js:9:19)
    at C:\Users\calic\Downloads\Vanilla-Updater-master\Vanilla-Updater-master\index.js:53:7
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sasial-dev** [comment]
@Alpha-404 Where is your folder with the installer?
(Also, if you have a discord account, please let me know so I can contact you easier! I'm Sasial#9375)

**Comment by heapframe** [comment]
@sasial-dev my discord is Terminated Egg#4125 also my installer is in downloads

**Comment by Water261** [comment]
Just putting it here for people to see, since it's setup using .. it needs to be in a specific place. Easiest way to do this is to open up index.js and change the lines which have "../Roblox/Versions" to "C:\\Users\\**YOUR USER HERE**\\AppData\\Local\\Roblox\\Versions" It's not ideal but it works.
