### ISSUE TITLE
Error when selecting color and theme

### ISSUE THREAD

**Issue by AlejandroDZ18** [DamnMerc/Vanilla-Updater#4]
Looks like theres a New Error again. Last time it worked but now it dosent. It gives me an Error when i select my theme and color

TypeError: Cannot read property 'forEach' of undefined

**Comment by LordMerc** [comment]
Use the updated code in https://github.com/DamnMerc/Vanilla-Updater/blob/master/index.js, there was an indent error that broke.

**Comment by AlejandroDZ18** [comment]
Thanks it worked!

**Comment by LordMerc** [comment]
No problem!
